
services:
  woodpecker-server:
    image: woodpeckerci/woodpecker-server:v3
    restart: unless-stopped
    volumes:
      - "{{woodpecker_data_dir}}:/var/lib/woodpecker/"
    environment:
      - WOODPECKER_OPEN={{woodpecker_open}}
      - WOODPECKER_HOST=https://{{woodpecker_host}}
      - WOODPECKER_ORGS={{woodpecker_orgs}}
      - WOODPECKER_ADMIN={{woodpecker_admin}}
      - WOODPECKER_REPO_OWNERS={{woodpecker_repo_owners}}
      - WOODPECKER_GITHUB={{woodpecker_github}}
      - WOODPECKER_GITHUB_CLIENT={{woodpecker_github_client_id}}
      - WOODPECKER_GITHUB_SECRET={{woodpecker_github_client_secret}}
      - WOODPECKER_AGENT_SECRET={{woodpecker_agent_secret}}
      - WOODPECKER_PLUGINS_PRIVILEGED={{woodpecker_plugins_privileged}}
      - WOODPECKER_DISABLE_USER_AGENT_REGISTRATION=true
      - WOODPECKER_ENABLE_SWAGGER=false
    networks:
      - databuddy_ci
      - databuddy_ingress
    deploy:
      mode: global
      update_config:
        parallelism: 0
        order: stop-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints:
          - node.labels.ci-root==true
      labels:
      - "traefik.enable=true"
      - "traefik.http.routers.woodpecker-server.rule=Host(`{{woodpecker_host}}`)"
      - "traefik.http.routers.woodpecker-server.entrypoints=websecure"
      - "traefik.http.routers.woodpecker-server.tls.certresolver=defaultResolver"
      - "traefik.http.services.woodpecker-server.loadbalancer.server.port=8000"
      - "traefik.docker.network=databuddy_ingress"

  woodpecker-agent:
    image: woodpeckerci/woodpecker-agent:v3
    command: agent
    restart: unless-stopped
    depends_on:
      - woodpecker-server
    volumes:
      - "{{woodpecker_agent_data_dir}}:/etc/woodpecker"
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WOODPECKER_SERVER=woodpecker-server:9000
      - WOODPECKER_AGENT_SECRET={{woodpecker_agent_secret}}
    networks:
      - databuddy_ci
    deploy:
      mode: global
      update_config:
        parallelism: 0
        order: stop-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints:
          - node.labels.ci-worker==true

networks:
  databuddy_ci:
    name: databuddy_ci
    driver: overlay
    driver_opts:
      encrypted: "true"
  databuddy_ingress:
    external: true
  
