---
- hosts: ingress
  name: "Deploy SSL Certificates"
  remote_user: root
  gather_facts: yes
  become: no    
  vars:
    working_dir_name: ingress
    reverse_proxy_data_dir: /data/ingress

  tasks:
    
    - name: Create Deployment Dir Ingress
      become: yes
      ansible.builtin.file:
        path: "{{working_dir_name}}"
        state: directory
        owner: root
        group: root
        mode: "0775"
        recurse: yes
      run_once: true
      delegate_to: "{{ (groups['swarm-managers'][0]) }}"
    
    - name: "Copy certificate file into server"
      ansible.builtin.template:
        src: ./databuddy_cc_star.crt
        dest: "{{working_dir_name}}/databuddy_cc_star.crt" 
      run_once: true
      delegate_to: "{{ (groups['swarm-managers'][0]) }}"
     
    - name: "Copy key file into server"
      ansible.builtin.template:
        src: ./databuddy_cc_star.key
        dest: "{{working_dir_name}}/databuddy_cc_star.key" 
      run_once: true
      delegate_to: "{{ (groups['swarm-managers'][0]) }}"
      
    - name: "Create/Update Certificate Secret"
      community.docker.docker_secret:
        name: databuddy_cc_star_cert
        data_src: "{{working_dir_name}}/databuddy_cc_star.crt"
        state: present
      run_once: true
      delegate_to: "{{ (groups['swarm-managers'][0]) }}"
    
    - name: "Create/Update Key Secret"
      community.docker.docker_secret:
        name: databuddy_cc_star_key
        data_src: "{{working_dir_name}}/databuddy_cc_star.key"
        state: present
      run_once: true
      delegate_to: "{{ (groups['swarm-managers'][0]) }}"

  
