---
- hosts: ingress
  name: "Deploy Ingress"
  remote_user: root
  gather_facts: yes
  become: no    
  vars:
    working_dir_name: ingress
    reverse_proxy_data_dir: /data/ingress

  tasks:
    - name: Create Data Dir reverse-proxy
      become: yes
      ansible.builtin.file:
        path: "{{reverse_proxy_data_dir}}"
        state: directory
        mode: "0600"
        recurse: yes
    
    - name: Create Deployment Dir Ingress
      become: yes
      ansible.builtin.file:
        path: "{{working_dir_name}}"
        state: directory
        owner: root
        group: root
        mode: "0775"
        recurse: yes
      run_once: true
      delegate_to: "{{ (groups['swarm-managers'][0]) }}"
    
    - name: "Copy docker compose into server"
      ansible.builtin.template:
        src: ./docker-compose.yaml
        dest: "{{working_dir_name}}/docker-compose.yaml" 
      run_once: true
      delegate_to: "{{ (groups['swarm-managers'][0]) }}"
    
    - name: "Copy Traefik Config to Server"
      ansible.builtin.template:
        src: ./traefik-config.yaml
        dest: "{{working_dir_name}}/traefik-config.yaml" 
      run_once: true
      delegate_to: "{{ (groups['swarm-managers'][0]) }}"
    
    - name: Create or Update Traefik Config
      community.docker.docker_config:
        name: traefik_config
        data_src: "{{working_dir_name}}/traefik-config.yaml"
        state: present
      run_once: true
      delegate_to: "{{ (groups['swarm-managers'][0]) }}"

    - name: "Start Stack"
      docker_stack:
        state: present
        with_registry_auth: yes
        prune: yes
        resolve_image: always
        name: "databuddy_ingress"
        compose:
          - "{{working_dir_name}}/docker-compose.yaml"
      run_once: true
      delegate_to: "{{ (groups['swarm-managers'][0]) }}"