networks:
  databuddy_ingress:
    driver: overlay
    driver_opts:
      encrypted: "true"
    attachable: true
    name: databuddy_ingress

services:
  reverse-proxy:
    # Use Traefik for routing and certificate handling.
    image: traefik:v3.4.0
    restart: unless-stopped
    command:
      - "--api.insecure=true"
      - "--providers.swarm=true"
      - "--providers.swarm.endpoint=unix:///var/run/docker.sock"
      - "--providers.swarm.exposedbydefault=false"
      - "--providers.file.filename=/config/traefik.yaml"
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http.tls=true
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --entryPoints.websecure.transport.respondingTimeouts.readTimeout=3600
      - --entryPoints.websecure.transport.respondingTimeouts.writeTimeout=3600
      - --entryPoints.websecure.transport.respondingTimeouts.idleTimeout=3600
      - --providers.swarm.network=databuddy_ingress
      - --accesslog=true
      - --accesslog.filters.statuscodes=300-399,400-499,500-599
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    networks:
      - databuddy_ingress
    volumes:
      - "{{reverse_proxy_data_dir}}:/letsencrypt"
      - /var/run/docker.sock:/var/run/docker.sock:ro
    secrets:
      - databuddy_cc_star_key
      - databuddy_cc_star_cert
    configs:
      - source: traefik_config
        target: /config/traefik.yaml
    deploy:
      mode: global
      update_config:
        parallelism: 0
        order: stop-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints:
          - node.labels.ingress==true
          - node.role == manager

secrets:
  databuddy_cc_star_key:
    external: true
  databuddy_cc_star_cert:
    external: true

configs:
  traefik_config:
    external: true
     