version: "3.9"
x-default-opts: 
  &default-opts
  logging:
    options:
      max-size: "10m"
services:       
    
  image-prune:
    <<: *default-opts
    image: docker
    command: sh -c "while true; sleep 3600; do docker image prune -af; sleep 86400; done"   
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: global
  
  system-prune:
    <<: *default-opts
    image: docker
    command: sh -c "while true; sleep 3600; do docker system prune -af; sleep 86400; done"   
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: global
  
  pgsql:
    image: postgres:17.5-alpine
    user: "{{postgres_uid}}:{{postgres_gid}}"
    environment:
      - POSTGRES_DB=databuddy
      - POSTGRES_PASSWORD=databuddy
    command: postgres -c 'max_connections=200' -c 'client_connection_check_interval=60000' -c tcp_keepalives_idle=600  -c tcp_keepalives_interval=20 -c tcp_keepalives_count=10
    stop_grace_period: 20m
    stop_signal: SIGINT
    networks:
      - databuddy_aqua
    volumes:
      - "{{postgresql_dir_name}}:/var/lib/postgresql/data"
      - type: tmpfs
        target: /dev/shm
        tmpfs:
           size: 256000000
    deploy:
      placement:
        constraints:
          - node.labels.pgsql==true
      replicas: 1
      update_config:
        parallelism: 0
        order: stop-first
        failure_action: rollback
        delay: 60s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    healthcheck:
      test: pg_isready -U postgres
      interval: 120s
      timeout: 60s
      start_period: 180s
      retries: 20
  
  redis:
    image: redis:7.4.1-alpine3.20
    user: "{{postgres_uid}}:{{postgres_gid}}"
    restart: unless-stopped
    healthcheck:
      test: redis-cli --raw incr ping
      interval: 60s
      retries: 5
      start_period: 60s
      timeout: 10s
    networks:
      - databuddy_aqua
    stop_grace_period: 20m
    stop_signal: SIGKILL
    expose:
      - 6379
    environment:
      - REDIS_DB=0
      - REDIS_PORT=6379
    command: >
      --bind 0.0.0.0
      --protected-mode no
      --tcp-backlog 511
      --timeout 0
      --tcp-keepalive 300
      --daemonize no
      --loglevel notice
      --always-show-logo no
      --stop-writes-on-bgsave-error yes
    deploy:
      placement:
        constraints:
          - node.labels.redis==true
      replicas: 1
      update_config:
        parallelism: 0
        order: stop-first
        failure_action: rollback
        delay: 60s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
  

  clickhouse:
    image: clickhouse/clickhouse-server
    user: "{{postgres_uid}}:{{postgres_gid}}"
    environment:
      - CLICKHOUSE_DB=databuddy
      - CLICKHOUSE_USER=databuddy
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
      - CLICKHOUSE_PASSWORD=databuddy
    expose:
      - 9000
      - 8123
    stop_grace_period: 20m
    stop_signal: SIGKILL
    networks:
      - databuddy_aqua
    volumes:
      - "{{clickhouse_dir_name}}:/var/lib/clickhouse"
      - "{{clickhouse_logs_dir_name}}:/var/log/clickhouse-server"
      - type: tmpfs
        target: /dev/shm
        tmpfs:
           size: 512000000
    ulimits:
      nofile:
        soft: 50000
        hard: 50000
    cap_add:
      - NET_ADMIN
      - IPC_LOCK
    deploy:
      placement:
        constraints:
          - node.labels.clickhouse==true
      replicas: 1
      update_config:
        parallelism: 0
        order: stop-first
        failure_action: rollback
        delay: 60s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://databuddy:databuddy@localhost:8123/?query=SELECT%201&database=databuddy || exit 1
      interval: 120s
      timeout: 60s
      start_period: 180s
      retries: 20

networks:
  databuddy_aqua:
    driver: overlay
    driver_opts:
      encrypted: "true"
    attachable: true
    name: databuddy_aqua