version: '3'
services:
  registry:
    image: registry:3.0.0
    command: /etc/distribution/config.yml
    expose:
      - 5000
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry
      REGISTRY_AUTH_HTPASSWD_PATH: /run/secrets/registry_password_file
      REGISTRY_STORAGE_DELETE_ENABLED: 1
      OTEL_TRACES_EXPORTER: none
      REGISTRY_LOG_LEVEL: info
    secrets:
      - registry_password_file
    volumes:
      - "{{registry_data_dir}}:/var/lib/registry"
    restart: always
    networks:
      - databuddy_ingress
    deploy:
      mode: global
      update_config:
        parallelism: 0
        order: stop-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints:
          - node.labels.ci-root==true
      labels:
      - "traefik.enable=true"
      - "traefik.http.routers.registry.rule=Host(`{{registry_host}}`)"
      - "traefik.http.routers.registry.entrypoints=websecure"
      - "traefik.http.services.registry.loadbalancer.server.port=5000"
      - "traefik.docker.network=databuddy_ingress"

networks:
  databuddy_ingress:
    external: true

secrets:
  registry_password_file:
    external: true