---
- hosts: "{{deployment_target}}"
  name: "Deploy App Stack"
  gather_facts: true
  environment: 
    PIP_BREAK_SYSTEM_PACKAGES: 1
  vars:
    working_dir_name: "databuddy-app"
    version: "{{version | default('latest')}}"
    api_host: beta-api.databyddy.cc
    basket_host: beta-basket.databuddy.cc
    dashboard_host: beta-app.databuddy.cc
    
  tasks:
    - name: "Copy docker compose into server"
      ansible.builtin.template:
        src: ./docker-compose.yaml
        dest: "{{working_dir_name}}/docker-compose.yaml" 
      run_once: true
      delegate_to: "{{ (groups['swarm-managers'][0]) }}"
    
    - name: "Start Stack"
      docker_stack:
        state: present
        with_registry_auth: yes
        prune: yes
        resolve_image: always
        name: "databuddy_app"
        compose:
          - "{{working_dir_name}}/docker-compose.yaml"
      run_once: true
      delegate_to: "{{ (groups['swarm-managers'][0]) }}"