---
- hosts: tool
  name: "Deploy Monitoring"
  remote_user: root
  gather_facts: yes
  become: no    
  vars:
    working_dir_name: monitoring
    couchdb_uid: "5984"
    couchdb_gid: "5984"
    influxdb_uid: "5985"
    influxdb_gid: "5985"
    swarmpit_proxy_oauth2_client_id: "Ov23liiPx9idZu9y4lzb"
    swarmpit_proxy_oauth2_client_secret: "7b9e9a4b7421beed1143b0eeebe9c25c0ee81c9f"
    swarmpit_proxy_ouath2_cookie_secret: "7qo4OPrCfklwHvrvw49UgZIupsFQN7JrT3pPBn8O48E="
    swarmpit_host: "swarmpit.databuddy.cc"

  tasks:
    - name: Create Deployment Dir Monitoring
      become: yes
      ansible.builtin.file:
        path: "{{working_dir_name}}"
        state: directory
        owner: root
        group: root
        mode: "0775"
        recurse: yes
      run_once: true
      delegate_to: "{{ (groups['swarm-managers'][0]) }}"
    
    - name: Create couchdb group
      become: yes
      group:
        name: "couchdb"
        gid: "{{couchdb_gid}}"
        state: present
      when: inventory_hostname in groups['monitoring-root']

    - name: Create couchdb Users Task
      become: yes
      user:
        name: "couchdb"
        uid: "{{couchdb_uid}}"
        state: present
        create_home: false
        shell: /sbin/nologin
        groups: "couchdb"
        append: yes
      when: inventory_hostname in groups['monitoring-root']
      
    - name: Create influxdb group
      become: yes
      group:
        name: "influxdb"
        gid: "{{influxdb_gid}}"
        state: present
      when: inventory_hostname in groups['monitoring-root']

    - name: Create influxdb Users Task
      become: yes
      user:
        name: "influxdb"
        uid: "{{influxdb_uid}}"
        state: present
        create_home: false
        shell: /sbin/nologin
        groups: "influxdb"
        append: yes
      when: inventory_hostname in groups['monitoring-root']

    - name: Create Data Dir For Swarmpit influxdb
      become: true
      ansible.builtin.file:
        path: "/data/swarmpit/influxdb"
        state: directory
        mode: "0775"
        owner: "{{influxdb_uid}}"
        group: "{{influxdb_gid}}"
        recurse: yes
      when: inventory_hostname in groups['monitoring-root']

    - name: Create Data Dir For Swarmpit couchdb
      become: true
      ansible.builtin.file:
        path: "/data/swarmpit/couchdb"
        state: directory
        mode: "0775"
        owner: "{{couchdb_uid}}"
        group: "{{couchdb_gid}}"
        recurse: yes
      when: inventory_hostname in groups['monitoring-root']
    
    - name: "Copy docker compose into server"
      ansible.builtin.template:
        src: ./docker-compose.yaml
        dest: "{{working_dir_name}}/docker-compose.yaml" 
      run_once: true
      delegate_to: "{{ (groups['swarm-managers'][0]) }}"
    
    - name: "Start Stack"
      docker_stack:
        state: present
        with_registry_auth: yes
        prune: yes
        resolve_image: always
        name: "databuddy_monitoring"
        compose:
          - "{{working_dir_name}}/docker-compose.yaml"
      run_once: true
      delegate_to: "{{ (groups['swarm-managers'][0]) }}"