---
- hosts: "{{deployment_target}}"
  name: "Deploy App Stack"
  gather_facts: no
  environment: 
    PIP_BREAK_SYSTEM_PACKAGES: 1
  vars:
    working_dir_name: "databuddy-app"
    version: "{{version | default('latest')}}"
    api_host: beta-api.databyddy.cc
    basket_host: beta-basket.databuddy.cc
    dashboard_host: beta-app.databuddy.cc
    
  tasks:
    - name: Log into private registry and force re-authorization
      community.docker.docker_login:
        registry_url: registry.databuddy.cc
        username: "{{docker_username}}"
        password: "{{docker_password}}"
        reauthorize: true
      run_once: true
      delegate_to: "{{ (groups['swarm-managers'][0]) }}"

    - name: Create Deployment Dir Databuddy App
      become: yes
      ansible.builtin.file:
        path: "{{working_dir_name}}"
        state: directory
        owner: root
        group: root
        mode: "0775"
        recurse: yes
      run_once: true
      delegate_to: "{{ (groups['swarm-managers'][0]) }}"

    - name: "Copy docker compose into server"
      ansible.builtin.template:
        src: ./docker-compose.yaml
        dest: "{{working_dir_name}}/docker-compose.yaml" 
      run_once: true
      delegate_to: "{{ (groups['swarm-managers'][0]) }}"
    
    - name: "Start Stack"
      docker_stack:
        state: present
        with_registry_auth: yes
        prune: yes
        resolve_image: always
        name: "databuddy_app"
        compose:
          - "{{working_dir_name}}/docker-compose.yaml"
      run_once: true
      delegate_to: "{{ (groups['swarm-managers'][0]) }}"