when:
  - event: tag
    branch: main

steps:

  - name: Build dashboard
    image: woodpeckerci/plugin-docker-buildx:6.0.0
    settings:
      registry: http://registry.databuddy.cc/v2
      repo: registry.databuddy.cc/dashboard
      dockerfile: dashboard.Dockerfile
      auto_tag: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

  - name: Build API
    image: woodpeckerci/plugin-docker-buildx:6.0.0
    settings:
      registry: http://registry.databuddy.cc/v2
      repo: registry.databuddy.cc/api
      dockerfile: api.Dockerfile
      auto_tag: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

  - name: Build Basket
    image: woodpeckerci/plugin-docker-buildx:6.0.0
    settings:
      registry: http://registry.databuddy.cc/v2
      repo: registry.databuddy.cc/basket
      dockerfile: basket.Dockerfile
      auto_tag: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
  
  - name : Deploy With Ansible
    image: woodpeckerci/plugin-ansible
    settings:
      playbook: infrastructure/deploy/deploy-databuddy.yaml
      diff: false
      inventory: infrastructure/inventory.ini
      syntax_check: false
      user: root
      private_key:
        from_secret: ansible_private_key
      galaxy: infrastructure/requirements.yaml
      extra_vars:
        ipinfo_token:
          from_secret: ipinfo_token
        ai_api_key:
          from_secret: ai_api_key
        better_auth_url:
          from_secret: better_auth_url
        better_auth_secret:
          from_secret: better_auth_secret
        github_client_id:
          from_secret: github_client_id
        github_client_secret:
          from_secret: github_client_secret
        google_client_id:
          from_secret: google_client_id
        google_client_secret:
          from_secret: google_client_secret
        opr_api_key:
          from_secret: opr_api_key
        docker_username:
          from_secret: docker_username
        docker_password:
          from_secret: docker_password
        deployment_target: infra-nodes
        version: ${CI_COMMIT_TAG}
  
  

  
  

