when:
  - event: tag
    branch: main

steps:

  - name : Deploy With Ansible
    image: woodpeckerci/plugin-ansible
    commands:
      - apk add make
      - cd infrastructure && make deploy-app

  - name: Build dashboard
    image: woodpeckerci/plugin-docker-buildx:6.0.0
    settings:
      registry: http://registry.databuddy.cc/v2
      repo: registry.databuddy.cc/dashboard
      dockerfile: dashboard.Dockerfile
      auto_tag: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

  - name: Build API
    image: woodpeckerci/plugin-docker-buildx:6.0.0
    settings:
      registry: http://registry.databuddy.cc/v2
      repo: registry.databuddy.cc/api
      dockerfile: api.Dockerfile
      auto_tag: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

  - name: Build Basket
    image: woodpeckerci/plugin-docker-buildx:6.0.0
    settings:
      registry: http://registry.databuddy.cc/v2
      repo: registry.databuddy.cc/basket
      dockerfile: basket.Dockerfile
      auto_tag: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
  
  

  
  

