# Linting Check for Pull Requests
#
# This workflow runs code quality checks on all pull requests to ensure
# consistent code style and catch potential issues before they're merged.
# It uses Biome for linting with the configuration from biome.jsonc.
#
name: Lint

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]
  merge_group:
    branches: [ "main" ]

permissions:
  contents: read
  pull-requests: write

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.2.19

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('bun.lock') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install dependencies
        run: bun install

      - name: Run lint check
        run: bun run lint